# Generated by Django 3.2.6 on 2021-08-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MobileCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='WindowModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.FloatField(verbose_name='Price')),
                ('little_about', models.TextField(verbose_name='Little About')),
                ('more_about', models.TextField(verbose_name='More About')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='windows', to='smartphones.mobilecategorymodel', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Window',
                'verbose_name_plural': 'Windows',
            },
        ),
        migrations.CreateModel(
            name='ProtectionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.FloatField(verbose_name='Price')),
                ('little_about', models.TextField(verbose_name='Little About')),
                ('more_about', models.TextField(verbose_name='More About')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='protections', to='smartphones.mobilecategorymodel', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Protection',
                'verbose_name_plural': 'Protections',
            },
        ),
        migrations.CreateModel(
            name='PhoneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='phone', verbose_name='Image')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.FloatField(verbose_name='Price')),
                ('little_about', models.TextField(verbose_name='Little About')),
                ('more_about', models.TextField(verbose_name='More About')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='phones', to='smartphones.mobilecategorymodel', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
            },
        ),
    ]
