# Generated by Django 3.2.6 on 2021-08-27 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartwatchCategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Smartwatch Category',
                'verbose_name_plural': 'Smartwatch Categories',
            },
        ),
        migrations.CreateModel(
            name='SmartwatchModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Chargers', verbose_name='Chargers')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('price', models.FloatField(verbose_name='Price')),
                ('little_about', models.TextField(verbose_name='Little About')),
                ('more_about', models.TextField(verbose_name='More About')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='smartwatches', to='smartwatches.smartwatchcategorymodel', verbose_name='Category')),
            ],
            options={
                'verbose_name': 'Smartwatch',
                'verbose_name_plural': 'Smartwatches',
            },
        ),
    ]
